TITLE = "simple_target"
MAPFILE = "simulation/map.txt"

GREEN = (0, 100, 0)
GREY = (100, 100, 100)
BLACK = (0, 0, 0)
BROWN = (139,69,19)

SCREEN_WIDTH = 650
SCREEN_HEIGHT = 550

NUMBER_OF_BLOCKS_WIDE = 13
NUMBER_OF_BLOCKS_HIGH = 11

BLOCK_HEIGHT = round(SCREEN_HEIGHT / NUMBER_OF_BLOCKS_HIGH)
BLOCK_WIDTH = round(SCREEN_WIDTH / NUMBER_OF_BLOCKS_WIDE)
